extends:
  - airbnb

rules:
  import/no-extraneous-dependencies: 0
  arrow-body-style: 0
  indent: 0
  prefer-arrow-callback: 1
  spaced-comment: 0
  space-before-function-paren: [2, "never"]
  no-param-reassign: 0
  vars-on-top: 0
  max-len: 0
  global-require: 0
  array-callback-return: 0
  consistent-return: 0
  no-underscore-dangle: 0
  no-use-before-define: [2, { "functions": false, "classes": true }]
  no-plusplus: 0
  radix: 1
  no-extend-native: 1
  no-shadow: 0
  no-console: 0
  comma-dangle: ["error", {
    "arrays": "always-multiline",
    "objects": "always-multiline",
    "imports": "always-multiline",
    "exports": "always-multiline",
    "functions": "ignore",
  }]
