language: node_js

node_js:
  - "6"

notifications:
  email: false

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - yarn build

after_success:
  - bash deploy.sh
